repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=50]
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --strict
          - >
            -d={extends: default, rules: {
            document-start: disable,
            quoted-strings: {quote-type: single, required: only-when-needed},
            truthy: {check-keys: false}}}

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=100
          - --select=A,B,C,E,EM,ERA,F,I,NPY,PD,PTH,SIM,UP,W
          - --ignore=T201,PD901
          - --no-cache
      - id: ruff-format
        args:
          - --line-length=100
          - --no-cache

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/meliache/pre-commit-chktex
    rev: v0.2.2
    hooks:
      - id: chktex-conda
        args: [-H, -I]
